// ErrorHandling.h

// SPDX-FileCopyrightText: 2022-2023, Yaskawa America, Inc.
// SPDX-FileCopyrightText: 2022-2023, Delft University of Technology
//
// SPDX-License-Identifier: Apache-2.0

#ifndef MOTOROS2_ERROR_HANDLING_H
#define MOTOROS2_ERROR_HANDLING_H

//**********************************************************************
//**********************************************************************
// MOTION FAILURE ERROR CODES
//**********************************************************************
//**********************************************************************

typedef enum
{
    MOTION_READY = motoros2_interfaces__msg__MotionReadyEnum__READY,
    MOTION_NOT_READY_UNSPECIFIED = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_UNSPECIFIED,
    MOTION_NOT_READY_ALARM = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_ALARM,
    MOTION_NOT_READY_ERROR = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_ERROR,
    MOTION_NOT_READY_ESTOP = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_ESTOP,
    MOTION_NOT_READY_NOT_PLAY = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_NOT_PLAY,
    MOTION_NOT_READY_NOT_REMOTE = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_NOT_REMOTE,
    MOTION_NOT_READY_SERVO_OFF = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_SERVO_OFF,
    MOTION_NOT_READY_HOLD = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_HOLD,
    MOTION_NOT_READY_NOT_STARTED = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_JOB_NOT_STARTED,
    MOTION_NOT_READY_WAITING_ROS = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_NOT_ON_WAIT_CMD,
    MOTION_NOT_READY_PFL_ACTIVE = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_PFL_ACTIVE,
    MOTION_NOT_READY_INC_MOVE_ERROR = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_INC_MOVE_ERROR,
    MOTION_NOT_READY_OTHER_PROGRAM_RUNNING = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_OTHER_PROGRAM_RUNNING,
    MOTION_NOT_READY_OTHER_TRAJ_MODE_ACTIVE = motoros2_interfaces__msg__MotionReadyEnum__NOT_READY_OTHER_TRAJ_MODE_ACTIVE,
} MotionNotReadyCode;

typedef enum
{
    INIT_TRAJ_OK = 0,
    INIT_TRAJ_TOO_SMALL = 200,
    INIT_TRAJ_TOO_BIG,
    INIT_TRAJ_ALREADY_IN_MOTION,
    INIT_TRAJ_INVALID_STARTING_POS,
    INIT_TRAJ_INVALID_VELOCITY,
    INIT_TRAJ_INVALID_JOINTNAME,
    INIT_TRAJ_INCOMPLETE_JOINTLIST,
    INIT_TRAJ_INVALID_TIME,
    INIT_TRAJ_WRONG_MODE,
    INIT_TRAJ_BACKWARD_TIME,
    INIT_TRAJ_WRONG_NUMBER_OF_POSITIONS,
    INIT_TRAJ_WRONG_NUMBER_OF_VELOCITIES,
    INIT_TRAJ_INVALID_ENDING_VELOCITY,
    INIT_TRAJ_INVALID_ENDING_ACCELERATION,
} Init_Trajectory_Status;

typedef enum
{
    FAIL_TRAJ_CANCEL = 300,
    FAIL_TRAJ_POSITION,
    FAIL_TRAJ_TIME,
    FAIL_TRAJ_ALARM,
} Failed_Trajectory_Status;

//**********************************************************************
//**********************************************************************
// TEACH-PENDANT ALARM CODES
//**********************************************************************
//**********************************************************************

#define ERROR_MSG_MAX_SIZE 32

//===================================
//Main Codes
//===================================
typedef enum
{
    ALARM_TASK_CREATE_FAIL = 8010,
    ALARM_ASSERTION_FAIL,
    ALARM_ALLOCATION_FAIL,
    ALARM_CONFIGURATION_FAIL,
    ALARM_INFORM_JOB_FAIL,
} ALARM_MAIN_CODE;


//===================================
//Sub Codes
//===================================
typedef enum
{
    SUBCODE_INITIALIZATION,
    SUBCODE_EXECUTOR,
    SUBCODE_INCREMENTAL_MOTION,
    SUBCODE_ADD_TO_INC_Q,
} TASK_CREATE_FAIL_SUBCODE;

typedef enum
{
    SUBCODE_FAIL_ROS_CONTROLLER_INIT,
    SUBCODE_INVALID_AXIS_TYPE,
    SUBCODE_FAIL_OPTIONS_INIT,
    SUBCODE_FAIL_RMW_OPTIONS_INIT,
    SUBCODE_FAIL_SUPPORT_INIT,
    SUBCODE_FAIL_NODE_INIT,
    SUBCODE_FAIL_MEM_ALLOC_CFG,
    SUBCODE_FAIL_CREATE_PUBLISHER_JOINT_STATE,
    SUBCODE_FAIL_CREATE_PUBLISHER_JOINT_STATE_ALL,
    SUBCODE_FAIL_CREATE_PUBLISHER_TRANSFORM,

    SUBCODE_FAIL_CREATE_PUBLISHER_ROBOT_STATUS,
    SUBCODE_FAIL_CREATE_TIMER,
    SUBCODE_FAIL_ALLOCATE_TRANSFORM,
    SUBCODE_FAIL_IO_STATUS_UPDATE,
    SUBCODE_FAIL_OPTIONS_INIT_DOMAIN_ID,
    SUBCODE_CONFIGURATION_INVALID_DOMAIN_ID,
    SUBCODE_CONFIGURATION_MISSING_AGENT_IP,
    SUBCODE_CONFIGURATION_INVALID_AGENT_SUBNET,
    SUBCODE_FAIL_ROS_CONTROLLER_INIT_TOO_MANY_GROUPS,
    SUBCODE_FAIL_MP_NICDATA,

    SUBCODE_MULTIPLE_INSTANCES_DETECTED,
    SUBCODE_CONFIGURATION_INVALID_NODE_NAME,
    SUBCODE_CONFIGURATION_INVALID_JOB_NAME,
    SUBCODE_FAIL_CREATE_SERVICE_QUEUE_POINT,
    SUBCODE_FAIL_TIMER_INIT_PING,
    SUBCODE_FAIL_TIMER_INIT_ROBOT_FB,
    SUBCODE_FAIL_TIMER_INIT_ACTION_FB,
    SUBCODE_FAIL_CREATE_MOTION_EXECUTOR,
    SUBCODE_FAIL_TIMER_ADD_PING,
    SUBCODE_FAIL_TIMER_ADD_ROBOT_FB,

    SUBCODE_FAIL_TIMER_ADD_ACTION_FB,
    SUBCODE_FAIL_ADD_FJT_SERVER,
    SUBCODE_FAIL_ADD_SERVICE_STOP_TRAJ,
    SUBCODE_FAIL_ADD_SERVICE_READ_SINGLE_IO,
    SUBCODE_FAIL_ADD_SERVICE_READ_GROUP_IO,
    SUBCODE_FAIL_ADD_SERVICE_WRITE_SINGLE_IO,
    SUBCODE_FAIL_ADD_SERVICE_WRITE_GROUP_IO,
    SUBCODE_FAIL_ADD_SERVICE_READ_M_REG,
    SUBCODE_FAIL_ADD_SERVICE_WRITE_M_REG,
    SUBCODE_FAIL_ADD_SERVICE_RESET_ERROR,

    SUBCODE_FAIL_ADD_SERVICE_START_TRAJ_MODE,
    SUBCODE_FAIL_ADD_SERVICE_START_QUEUE_MODE,
    SUBCODE_FAIL_ADD_SERVICE_QUEUE_POINT,
    SUBCODE_FAIL_INIT_SERVICE_READ_SINGLE_IO,
    SUBCODE_FAIL_INIT_SERVICE_READ_GROUP_IO,
    SUBCODE_FAIL_INIT_SERVICE_WRITE_SINGLE_IO,
    SUBCODE_FAIL_INIT_SERVICE_WRITE_GROUP_IO,
    SUBCODE_FAIL_INIT_SERVICE_READ_M_REG,
    SUBCODE_FAIL_INIT_SERVICE_WRITE_M_REG,
    SUBCODE_FAIL_INIT_SERVICE_RESET_ERROR,

    SUBCODE_FAIL_INIT_SERVICE_START_TRAJ_MODE,
    SUBCODE_FAIL_INIT_SERVICE_START_QUEUE_MODE,
    SUBCODE_FAIL_INIT_SERVICE_STOP_TRAJ_MODE,
    SUBCODE_FAIL_ADD_SERVICE_SELECT_MOTION_TOOL,
    SUBCODE_FAIL_INIT_SERVICE_SELECT_MOTION_TOOL,

    SUBCODE_CONFIGURATION_EMPTY_JOINT_NAME,
    SUBCODE_FAIL_CREATE_IO_EXECUTOR,

    SUBCODE_FAIL_TIMER_INIT_USERLAN_MONITOR,
    SUBCODE_FAIL_TIMER_ADD_USERLAN_MONITOR,

    SUBCODE_CONFIGURATION_AGENT_ON_NET_CHECK,

} ASSERTION_SUBCODE;

typedef enum
{
    SUBCODE_ALLOCATION_MALLOC,
    SUBCODE_ALLOCATION_CALLOC,
    SUBCODE_ALLOCATION_REALLOC,
} ALLOCATION_SUBCODE;

typedef enum
{
    SUBCODE_CONFIGURATION_MISSINGFILE,
    SUBCODE_CONFIGURATION_SRAM_ACCESS_FAILURE,
    SUBCODE_CONFIGURATION_SRAM_WRITE_FAILURE,
    SUBCODE_CONFIGURATION_INVALID_BOOLEAN_VALUE,
    SUBCODE_CONFIGURATION_INVALID_QOS_VALUE,
    SUBCODE_CONFIGURATION_INVALID_EXECUTOR_PERIOD,
    SUBCODE_CONFIGURATION_INVALID_FEEDBACK_PERIOD,
    SUBCODE_CONFIGURATION_INVALID_IO_PERIOD,
    SUBCODE_CONFIGURATION_TOO_MANY_REMAP_RULES1,
    SUBCODE_CONFIGURATION_TOO_MANY_REMAP_RULES2,
    SUBCODE_CONFIGURATION_INVALID_REMAP_RULE_FORMAT,
    SUBCODE_CONFIGURATION_FAIL_NODE_INIT_ARG_PARSE,
    SUBCODE_CONFIGURATION_INVALID_CUSTOM_JOINT_NAME,
    SUBCODE_CONFIGURATION_INVALID_USERLAN_MONITOR_PORT,
    SUBCODE_CONFIGURATION_USERLAN_MONITOR_AUTO_DETECT_FAILED,
    SUBCODE_CONFIGURATION_INVALID_USERLAN_MONITOR_MAX_NUM_DROPS,
    SUBCODE_CONFIGURATION_RUNTIME_USERLAN_LINKUP_ERR,
} CONFIGURATION_SUBCODE;

typedef enum
{
    SUBCODE_INFORM_FAIL_TO_OPEN_DRAM,
    SUBCODE_INFORM_INVALID_JOB,
    SUBCODE_INFORM_FAIL_TO_CREATE_JOB,
    SUBCODE_INFORM_FAIL_TO_LOAD_JOB,
} INFORM_SUBCODE;

extern void motoRosAssert(BOOL mustBeTrue, ASSERTION_SUBCODE subCodeIfFalse);
extern void motoRosAssert_withMsg(BOOL mustBeTrue, ASSERTION_SUBCODE subCodeIfFalse, char* msgFmtIfFalse, ...);

extern void Ros_ErrorHandling_ErrNo_ToString(int errNo, char* const errMsg, int errMsgSize);
extern const char* const Ros_ErrorHandling_MotionNotReadyCode_ToString(MotionNotReadyCode code);

#endif  // MOTOROS2_ERROR_HANDLING_H
