# SPDX-FileCopyrightText: 2023, Yaskawa America, Inc.
# SPDX-FileCopyrightText: 2023, Delft University of Technology
#
# SPDX-License-Identifier: CC0-1.0

name: "CI: lint MotoROS2 config"
on:
  pull_request:
  workflow_dispatch:
jobs:
  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: karancode/yamllint-github-action@v3.0.0
        with:
          yamllint_file_or_dir: 'config'
          yamllint_config_filepath: 'config/.yamllint'
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
